name: plasmabio-template-bash
channels:
  - conda-forge
dependencies:
  - jupyterlab=2
  - nbresuse
  - python>=3.7
  - pip
  - nodejs
  - tensorboard
  - tensorflow>=1.3
  - pip:
    - bash_kernel
    - ipython
    - jupyter-tensorboard
